#!/bin/bash -x
isparttime=1;
isfulltimw=2;
emprateperhour=20;
empcheck=$((RANDOM%3));
 case $empcheck in
   $isfulltime)
emphrs=8;;
$isparttime)
emphours=4;;
*)
emphrs=0;;
esac
salary=$(($emphrs*emprateperhour));

